services:
  web:
    volumes:
      - ./:/app
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "8001:8000"
    restart: "no"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    volumes:
      - ./:/app
    restart: "no"

  beat:
    volumes:
      - ./:/app
    restart: "no"

  db:
    ports:
      - "5438:5432"

  redis:
    ports:
      - "6380:6379"
